site_name: JS SDK API Reference
site_description: Document for SkyWay/ECLWebRTC JavaScript SDK
site_author: NTT Communications
site_url: 'https://webrtc.ecl.ntt.com/'
copyright: '© NTT Communications Corporation All Rights Reserved.'
pages:
    - Introduction: index.md
    - 日本語:
        - Peer: ja/peer.md
        - MediaConnection: ja/mediaconnection.md
        - DataConnection: ja/dataconnection.md
        - MeshRoom: ja/meshroom.md
        - SFURoom: ja/sfuroom.md
    - English:
        - Peer: en/peer.md
        - MediaConnection: en/mediaconnection.md
        - DataConnection: en/dataconnection.md
        - MeshRoom: en/meshroom.md
        - SFURoom: en/sfuroom.md
theme:
    name: 'material'
    language: 'en'
    logo: 'images/skyway-symbol.svg'
extra:
    search:
        language: 'jp'
extra_css:
    - 'css/custom.css'
markdown_extensions:
    - codehilite
    - toc:
        permalink: true
extra:
  social:
    - type: home
      link: https://webrtc.ecl.ntt.com/