version: 2
jobs:
   test:
     docker:
       - image: circleci/node:8.9.3
     steps:
       - checkout
       - run:
          name: Install npm
          command: npm install
       - run:
          name: Run Test (testlint)
          command: npm run test
   build:
     docker:
       - image: circleci/python:3.6.1
     working_directory: ~/repo
     steps:
       - checkout
       - add_ssh_keys:
           fingerprints:
             - "57:80:f7:fe:15:a2:0b:33:41:9c:e0:ad:30:66:22:2c"
       - run:
          name: Deploy to the production
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install mkdocs
            pip install mkdocs-material
            mkdocs build
            mkdocs gh-deploy
workflows:
  version: 2
  build_and_test:
    jobs:
      - test:
          filters:
            branches:
              ignore: gh-deploy
      - build:
          requires:
            - test
          filters:
            branches:
              only: master
